version: 1.0.13.{build}
os: Visual Studio 2015
configuration: CI
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
nuget:
  account_feed: true
  project_feed: true

before_build:
- cmd: dotnet restore

build:
  project: DocsByReflection.sln
  verbosity: normal

after_build:
- cmd: >-

    dotnet test ./DocsByReflection.UnitTests

    mkdir .\src\nuget

    dotnet pack .\DocsByReflection --version-suffix=%APPVEYOR_BUILD_NUMBER% --output .\nuget

artifacts:
  - path: .\nuget\*.nupkg
    name: NuGet packages
